name: Windows Build

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Recursive Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Setup CUDA
      uses: Jimver/cuda-toolkit@v0.2.8
      id: cuda-toolkit
      with:
        cuda: '11.2.0'
        
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCODEGEN_SHORTEN=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
